// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpyJe9GfkBro93lMHdUN6l0YEfAsAvmAk',
    appId: '1:445235194138:web:54f11d53ea0835b65ae4a3',
    messagingSenderId: '445235194138',
    projectId: 'yoinnapp',
    authDomain: 'yoinnapp.firebaseapp.com',
    storageBucket: 'yoinnapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI6gODh5uEkcpIuQVrKvD9xR0lFlBwrns',
    appId: '1:445235194138:android:aa25d98513a4c2215ae4a3',
    messagingSenderId: '445235194138',
    projectId: 'yoinnapp',
    storageBucket: 'yoinnapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2vgDkzEAcldr8SjMhk0fpgnSLlPcBB48',
    appId: '1:445235194138:ios:c23dd0a61cfe55855ae4a3',
    messagingSenderId: '445235194138',
    projectId: 'yoinnapp',
    storageBucket: 'yoinnapp.firebasestorage.app',
    iosBundleId: 'cl.yoinn.app',
    // AGREGADO MANUALMENTE SEGÚN TU CAPTURA
    iosClientId: '445235194138-s80pe11bldrgooj8n9m7a2jqk5tipq84.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2vgDkzEAcldr8SjMhk0fpgnSLlPcBB48',
    appId: '1:445235194138:ios:20fe477fa80a7b7c5ae4a3',
    messagingSenderId: '445235194138',
    projectId: 'yoinnapp',
    storageBucket: 'yoinnapp.firebasestorage.app',
    iosBundleId: 'com.example.yoinnApp',
    iosClientId: '445235194138-s80pe11bldrgooj8n9m7a2jqk5tipq84.apps.googleusercontent.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpyJe9GfkBro93lMHdUN6l0YEfAsAvmAk',
    appId: '1:445235194138:web:984b643fbda7fcd55ae4a3',
    messagingSenderId: '445235194138',
    projectId: 'yoinnapp',
    authDomain: 'yoinnapp.firebaseapp.com',
    storageBucket: 'yoinnapp.firebasestorage.app',
  );
}